minVersion: 0.28.1
changelogPolicy: simple
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  # NPM Release Target
  - name: npm
    id: "@sentry/conventions"
    includeNames: /^javascript\/sentry-conventions\/sentry-conventions.*\.tgz$/

  # pypi Release Targets
  - name: pypi
    includeNames: /^python\/dist\/.*\.whl$/
  
  # TODO: Uncomment after release to normal pypi
  # - name: sentry-pypi
  #  internalPypiRepo: getsentry/pypi

  # Google Cloud Storage Target
  # TODO: Uncomment this when we have a bucket for the model conventions json
  # - name: gcs
  #   id: "model-conventions-json"
  #   includeNames: /^model\/.*\.tgz$/
  #   bucket: sentry-conventions
  #   paths:
  #     - path: /{{version}}/
  #       metadata:
  #         cacheControl: "public, max-age=31536000"

  # Github Release Target
  - name: github
    includeNames: /^(javascript\/.*\.tgz|python\/dist\/.*\.whl|model\/.*\.tgz)$/
