minVersion: 0.28.1
changelogPolicy: simple
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  # NPM Release Target
  - name: npm
    id: "@sentry/conventions"
    includeNames: /sentry-conventions-v.*\.tgz$/

  # pypi Release Targets
  - name: pypi
    includeNames: /sentry_conventions.*\.whl$/
  - name: sentry-pypi
    includeNames: /sentry_conventions.*\.whl$/
    internalPypiRepo: getsentry/pypi

  # Google Cloud Storage Target
  # TODO: Uncomment this when we have a bucket for the model conventions json
  # - name: gcs
  #   id: "model-conventions-json"
  #   includeNames: /^model\/.*\.tgz$/
  #   bucket: sentry-conventions
  #   paths:
  #     - path: /{{version}}/
  #       metadata:
  #         cacheControl: "public, max-age=31536000"

  # Github Release Target
  - name: github
