groups:
  - id: sentry.database
    prefix: db
    type: span
    brief: >
      This document defines semantic convention attributes in the database namespace used by Sentry.
    attributes:
      - id: system
        in_otel: true
        type: string
        brief: >
          An identifier for the database management system (DBMS) product being used..
        examples: postgresql
      - id: operation
        type: string
        in_otel: true
        brief: >
          The name of the operation being executed, e.g. the MongoDB command name such as findAndModify, or the SQL keyword.
        examples: SELECT
      - id: name
        in_otel: true
        type: string
        brief: "This attribute is used to report the name of the database being accessed. For commands that switch the database, this should be set to the target database (even if the command fails)."
        examples: customers
  - id: sentry.database.server
      prefix: server
      type: span
      brief: >
        This document defines semantic convention attributes in the database server namespace used by Sentry.
      attributes:
        - id: address
          in_otel: true
          type: string
          brief: "Name of the database host."
          examples: example.com
        - id: port
          in_otel: true
          type: int
          brief: "Logical server port number host."
          examples: 5432
        - id: socket
          prefix: socket
          attributes:
            - id: address
              in_otel: true
              type: string
              brief: "Physical server IP address or Unix socket address. host."
              examples: "10.5.3.2"
            - id: port
              in_otel: true
              type: int
              brief: "Physical server port. host."
              examples: 16456
  - id: sentry.cache
    prefix: cache
    type: span
    brief: >
      This document defines semantic convention attributes in the cache namespace used by Sentry.
    attributes:
      - id: hit
        type: boolean
        brief: "If the cache was hit during this span."
        examples: true
      - id: item_size
        type: int
        brief: "The size of the requested item in the cache. In bytes."
        examples: 58
